### ISSUE TITLE
Viaplay in UK

### ISSUE THREAD

**Issue by kontell** [zuzia-dev/kodi-viaplay#1]
Viaplay.com has launched in the UK, is it possible to have it supported in the addon?

The activation URL is https://viaplay.com/gb/activate

Thanks

**Comment by zuzia-dev** [comment]
Requires testing: https://github.com/zuzia-dev/zuzia_srcs/raw/main/kodi-viaplay.zip

**Comment by kontell** [comment]
That was quick, thanks. All playback appears to work fine except subtitles aren't working.

It shows a single subtitle available - English - sami (External) (1/1) - but nothing shows when it is turned on.  
[kodi.log](https://github.com/zuzia-dev/kodi-viaplay/files/9954051/kodi.log)

**Comment by kontell** [comment]
I tested with a development build, the subtitles and everything else work fine on V19.

**Comment by CastagnaIT** [comment]
i have made the subtitle fix for kodi 20
https://github.com/xbmc/xbmc/pull/22123

someone can make a test for confirm and give a feedback?

if you cant build kodi, i can provide a test build, just let me know the operative system
more easy if for Windows64 / Android / Android64

**Comment by kontell** [comment]
No idea how to build Kodi, but if you provide me with an Android 64 apk I'll test it.

**Comment by CastagnaIT** [comment]
here: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20221112-6022a2bd-fix_sami-24901-arm64-v8a.apk

**Comment by kontell** [comment]
Thanks for that. 

The behaviour is a little weird, if I enable the subtitles some are displayed across the entire screen. They do not update, just stay on screen. 
![sami_subtitles](https://user-images.githubusercontent.com/91025994/201472397-926d241f-0228-461b-b1f4-2073c8c8f2bf.jpeg)

The playback and UI stutter badly and when I turn off subtitles the video speeds up/ re syncs to where it should be.

[kodi.log](https://github.com/zuzia-dev/kodi-viaplay/files/9994850/kodi.log)

I can test on Windows 10 if that's easier.

**Comment by CastagnaIT** [comment]
this is so weird,
if i download the original .sami file from the log and i try to play a video with it i can see subtitle correctly

i see that this addon download the subtitles,
so for now i have the suspect that what i manually download from log could be not the same subtitle data played by your kodi

Can you attach the sami download/saved to disk by the addon of the screenshot? compressed in a zip?
so i can make a comparison of data with the original (from url)
maybe addon maintainer can let you know where is the downloaded sub file?

> I can test on Windows 10 if that's easier.

if you prefeer windows next time i provide Windows build, change nothing for me

**Comment by kontell** [comment]
I can see that subtitles are downloaded to the below directory on Linux. But on my Android device there is no "plugin.video.viaplay" inside "userdata/addon_data".

.kodi/userdata/addon_data/plugin.video.viaplay/tmp

I downloaded the subtitles using V20 on Windows (they were not zipped).
[en.zip](https://github.com/zuzia-dev/kodi-viaplay/files/9995015/en.zip)

Another bit of weirdness, when I played that video the subtitles were shown on screen for a few seconds before disappearing and normal playback continuing.
![win10_devel_viaplay](https://user-images.githubusercontent.com/91025994/201475235-d48e101e-6841-4fd4-bf67-b73b29f9de0c.jpg)

**Comment by CastagnaIT** [comment]
thanks confirm same data
sorry for incovenience but its my fails
i forgot to update my local build to last commit i think to have done a mistake somewhere

**Comment by CastagnaIT** [comment]
New build here:
http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20221112-075e6dc6-fix_sami-24906-arm64-v8a.apk

**Comment by kontell** [comment]
Working fine now, thanks for the quick work.
