### ISSUE TITLE
Bug | Playlist Generator Error (UK)

### ISSUE THREAD

**Issue by kontell** [zuzia-dev/kodi-viaplay#3]
When attempting to create a playlist either from the addon settings or from IPTV merge I get an error, see below log.
[Viaplay_playlist_Kodi.log](https://github.com/zuzia-dev/kodi-viaplay/files/10303848/Viaplay_playlist_Kodi.log)

**Comment by zuzia-dev** [comment]
Thank you for your bug report. It worked great in the Polish version but unfortunately they just removed all TV channels from Viaplay PL. I also don't have any other foreign Vipalay subscriptions to check thoroughly. Until the issue has been resolved I suggest you roll back to  [version 3.8](https://github.com/zuzia-dev/kodi-viaplay/releases/tag/v2.3.8), there is the old method of generating the m3u list.

@ZefQ what is your version? British, Scandinavian or other?

**Comment by zuzia-dev** [comment]
Thank you for your bug report. It worked great in the Polish version but unfortunately they just removed all TV channels from Viaplay PL. I also don't have any other foreign Viaplay subscriptions to check thoroughly. Until the issue has been resolved I suggest you roll back to  [version 2.3.8](https://github.com/zuzia-dev/kodi-viaplay/releases/tag/v2.3.8), there is the old method of generating the m3u list.

@ZefQ what is your version? British, Scandinavian or other?

**Comment by kontell** [comment]
It's the British version I'm using, I hadn't used the playlist generator function before.

Viaplay doesn't show channels in the app, only live sport by individual event. If the addon is only supposed to generate a m3u from channels then I don't think there's really a bug.

If you want a login to test anything let me know.

**Comment by zuzia-dev** [comment]
>  If the addon is only supposed to generate a m3u from channels then I don't think there's really a bug.

Yes, the feature is only for live TV channels available in the Viaplay Total package. Such as Viaplay Xtra and others in TV category. 

> If you want a login to test anything let me know.

Thank you but maybe some other time. When something breaks in the British version. Everything seems to be fine now.

**Comment by ZefQ** [comment]
I'm using the Scandinavian version, and I have a "Tv channel" menu entry when browsing the web. maybe the British version don't? anyway it should not throw a error in the logs if there aren't any channels. so I will add some error handling at least, but right now om on the road so will look at it when i get home.

**Comment by kontell** [comment]
There's no "TV Channel" available on the British Viaplay website, you can only get the channels if you subscribe through Amazon Prime or a TV provider.
